'use client';

import { useEffect, useState } from 'react';
import OutfitCanvas from '../components/OutfitCanvas';

export default function WardrobePage() {
  const [items, setItems] = useState<any[]>([]);
  const [outfits, setOutfits] = useState<any[]>([]);
  const [outfitDetails, setOutfitDetails] = useState<any[]>([]);
  const [selectedItemImage, setSelectedItemImage] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [aiImage, setAiImage] = useState<string | null>(null);

  useEffect(() => {
    fetch('/api/clothing')
      .then(res => res.json())
      .then(data => {
        setItems(data.items || []);
        setLoading(false);
      });
  }, []);

  const generateOutfits = async (itemId: string) => {
    setGenerating(true);
    setAiImage(null);
    setOutfits([]);
    setOutfitDetails([]);
    
    const itemImage = items.find(i => i.id === itemId)?.image_url || '';
    setSelectedItemImage(itemImage);

    const res = await fetch('/api/generate-outfit', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        baseItemId: itemId,
        mode: 'shopping',
        preferences: { style: 'casual', budget: '100' }
      })
    });
    const data = await res.json();
    const newOutfits = data.outfits || [];
    setOutfits(newOutfits);
    
    if (newOutfits.length > 0) {
      const piecesRes = await fetch(`/api/outfit-pieces?outfitId=${newOutfits[0].id}`);
      const piecesData = await piecesRes.json();
      setOutfitDetails(piecesData.pieces || []);
    }
    setGenerating(false);
  };

  const loadOutfitPieces = async (outfitId: string) => {
    const res = await fetch(`/api/outfit-pieces?outfitId=${outfitId}`);
    const data = await res.json();
    setOutfitDetails(data.pieces || []);
  };

  const generateModelPhoto = async (outfitId: string) => {
    const res = await fetch('/api/virtual-display', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ outfitId })
    });
    const data = await res.json();
    if (data.imageUrl) setAiImage(data.imageUrl);
  };

  if (loading) return <div className="p-8 text-center">Loading your wardrobe...</div>;

  return (
    <div className="max-w-4xl mx-auto p-8">
      <h1 className="text-2xl font-bold mb-6">Your Wardrobe</h1>
      
      {items.length === 0 ? (
        <p className="text-gray-500">No items yet. <a href="/upload" className="text-blue-600 underline">Upload one first</a></p>
      ) : (
        <div className="grid grid-cols-3 gap-4 mb-8">
          {items.map(item => (
            <div key={item.id} className="border rounded-lg p-4 shadow-sm">
              <img src={item.image_url} className="w-full h-40 object-cover rounded mb-2" />
              <p className="font-bold capitalize">{item.category}</p>
              <p className="text-sm text-gray-600">{item.color} • {item.style}</p>
              <button
                onClick={() => generateOutfits(item.id)}
                className="mt-2 w-full bg-black text-white py-2 rounded text-sm hover:bg-gray-800"
              >
                {generating ? 'Styling...' : 'Style This Item'}
              </button>
            </div>
          ))}
        </div>
      )}

      {outfits.length > 0 && (
        <div className="mt-8">
          <h2 className="text-xl font-bold mb-4">Generated Outfits</h2>
          <div className="grid gap-4">
            {outfits.map((outfit: any) => (
              <div key={outfit.id} className="border p-4 rounded-lg bg-gray-50">
                <h3 className="font-bold text-lg">{outfit.name}</h3>
                <p className="text-sm text-gray-500 mb-2">Occasion: {outfit.occasion}</p>
                <div className="flex gap-2">
                  <button 
                    onClick={() => loadOutfitPieces(outfit.id)}
                    className="px-3 py-1 bg-white border rounded text-sm hover:bg-gray-100"
                  >
                    View Pieces
                  </button>
                  <button 
                    onClick={() => generateModelPhoto(outfit.id)}
                    className="px-3 py-1 bg-purple-600 text-white rounded text-sm hover:bg-purple-700"
                  >
                    AI Model Photo
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {aiImage && (
        <div className="mt-8 p-4 border rounded-lg bg-white">
          <h3 className="font-bold mb-2">AI Virtual Model</h3>
          <img src={aiImage} alt="AI Outfit" className="w-full max-w-md rounded-lg" />
          <p className="text-xs text-gray-500 mt-2">Generated by Pollinations.ai (Free)</p>
        </div>
      )}

      {outfitDetails.length > 0 && selectedItemImage && (
        <div className="mt-8 p-4 border rounded-lg bg-white">
          <h3 className="font-bold mb-4">Quick Outfit Sketch</h3>
          <OutfitCanvas baseImageUrl={selectedItemImage} pieces={outfitDetails} />
          
          <div className="mt-4 space-y-2">
            {outfitDetails.filter(p => !p.is_owned).map((piece: any) => (
              <div key={piece.id} className="p-2 bg-gray-50 rounded">
                <p className="font-semibold text-sm">{piece.role}: {piece.name}</p>
                {piece.shopping_links && (
                  <div className="flex gap-2 mt-1 flex-wrap">
                    {piece.shopping_links.map((link: any) => (
                      <a 
                        key={link.name} 
                        href={link.url} 
                        target="_blank" 
                        rel="noreferrer"
                        className="text-xs px-2 py-1 bg-blue-600 text-white rounded hover:bg-blue-700"
                      >
                        Shop {link.name}
                      </a>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}